### PR TITLE
added README_PROGRESS

### PR DESCRIPTION
**Pull request by mwigzell**
Hi LInas, this adds a progress readme with some pointers into the opencog and blender chat threads.

### CODE REVIEW

**Comment by mwigzell** [comment]
I realized I also added Eva_2.79b.blend which as I recall is identical to Sophia.blend. This was done so we can switch over from using "Sophia" in the repo.

**Comment by mwigzell** [comment]
oh, and of course, I'm not going anywhere: pls. do reach out if you need anything.

**Comment by linas** [comment]
Thanks! Like, oodles of thanks! I'm sorry it never arrived at a modern state. Hmm. Occurs to me, we never contacted the original author, Mike Pan. Wonder if he could have fixed it...

> reach out if you need anything.

Heh! What a thing to say! Write me a private email, I have ideas for other projects.

**Comment by mwigzell** [comment]
Well, if Mike Pan is available still, its worth contacting him I'd say.
What's his email address?

**Comment by linas** [comment]
> Well, if Mike Pan is available still, its worth contacting him I'd say.
> What's his email address?

It would be on his github profile. Be aware he was paid for the original work.
Hmm. I don't see an email, but I do see http://mikepan.com/

**Pull request merged**
